[package]
name = "i8051-test-runner"
version.workspace = true
edition.workspace = true
publish = false
readme = "README.md"

[dependencies]
i8051.workspace = true
i8051-debug-tui.workspace = true
clap = { version = "4.5", features = ["derive"] }

[[bin]]
name = "test-runner"
path = "src/main.rs"
